import 'bootstrap/dist/css/bootstrap.css'
import {Inter} from "next/font/google";
import "./globals.css";
import BoostrapClient from "@/app/_components/BootstrapClient";
import RestaurantHeader from "@/app/_components/RestaurantHeader";
import Footer from "@/app/_components/Footer";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
    title: "Food Delivery App",
    icons:{
      icon:"../public/logo/food-delivery-app.jpeg",
    },
    description: "Generated by create next app",
};


export default function RootLayout({children}) {
    return (
        <html lang="en">

        <body className={inter.className}>
        <RestaurantHeader/>
        {children}
        <Footer/>
        <BoostrapClient/>
        </body>
        </html>
    );
}
