import 'bootstrap/dist/css/bootstrap.css'
import { Inter } from "next/font/google";
import "./globals.css";
import BoostrapClient from "@/app/_components/BootstrapClient";
import RestaurantHeader from "@/app/_components/RestaurantHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
      <RestaurantHeader/>
      {children}
      <BoostrapClient/>
      </body>
    </html>
  );
}
